spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Weather?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# API Key
openweathermap:
  key: 2d5cfdd8c679d78e0ebb9c30d2506aaa

logging:
  config: classpath:logback-spring.xml
